# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1033, 403)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(670, 360, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(36, 140, 101, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 210, 121, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(540, 140, 141, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(560, 210, 111, 31))
        self.label_4.setObjectName("label_4")
        self.txt_Plaintext = QtWidgets.QTextEdit(Dialog)
        self.txt_Plaintext.setGeometry(QtCore.QRect(150, 110, 341, 71))
        self.txt_Plaintext.setObjectName("txt_Plaintext")
        self.txt_Ciphertext = QtWidgets.QTextEdit(Dialog)
        self.txt_Ciphertext.setGeometry(QtCore.QRect(150, 190, 341, 71))
        self.txt_Ciphertext.setObjectName("txt_Ciphertext")
        self.txt_Information = QtWidgets.QTextEdit(Dialog)
        self.txt_Information.setGeometry(QtCore.QRect(670, 110, 341, 71))
        self.txt_Information.setObjectName("txt_Information")
        self.txt_Signature = QtWidgets.QTextEdit(Dialog)
        self.txt_Signature.setGeometry(QtCore.QRect(670, 190, 341, 71))
        self.txt_Signature.setObjectName("txt_Signature")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(410, 0, 151, 61))
        self.label_5.setObjectName("label_5")
        self.btn_Encypt = QtWidgets.QPushButton(Dialog)
        self.btn_Encypt.setGeometry(QtCore.QRect(180, 280, 75, 23))
        self.btn_Encypt.setObjectName("btn_Encypt")
        self.btn_GenerateKeys = QtWidgets.QPushButton(Dialog)
        self.btn_GenerateKeys.setGeometry(QtCore.QRect(600, 20, 81, 21))
        self.btn_GenerateKeys.setObjectName("btn_GenerateKeys")
        self.btn_Decypt = QtWidgets.QPushButton(Dialog)
        self.btn_Decypt.setGeometry(QtCore.QRect(380, 280, 75, 23))
        self.btn_Decypt.setObjectName("btn_Decypt")
        self.btn_Sign = QtWidgets.QPushButton(Dialog)
        self.btn_Sign.setGeometry(QtCore.QRect(710, 280, 75, 23))
        self.btn_Sign.setObjectName("btn_Sign")
        self.btn_Verify = QtWidgets.QPushButton(Dialog)
        self.btn_Verify.setGeometry(QtCore.QRect(900, 280, 75, 23))
        self.btn_Verify.setObjectName("btn_Verify")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Plain Text:</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Cipher Text:</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Information:</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Signature:</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">RSA CIPHER</span></p></body></html>"))
        self.btn_Encypt.setText(_translate("Dialog", "Encrypt"))
        self.btn_GenerateKeys.setText(_translate("Dialog", "Generate Keys"))
        self.btn_Decypt.setText(_translate("Dialog", "Decypt"))
        self.btn_Sign.setText(_translate("Dialog", "Sign"))
        self.btn_Verify.setText(_translate("Dialog", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
